채팅 컴포넌트 백엔드 연결 테스트 중
exciting-transcendence/transcendence pull request #87
Opened 2022-08-14 06:16 UTC by peas856

![42_tr - 채팅](https://user-images.githubusercontent.com/42163769/184524848-3cace771-2155-422c-8068-7ceb5ee11d0c.png)
- 위와 같이 방만들기는 Public과 Private으로 나누고 Public의 경우 Protected로 설정할 수 있는 옵션을 제공할 예정입니다. 
- 방 만들 때 방 이름을 전달해야 합니다. 
- 왼쪽 하단에는 참여중인 방 리스트를 보여주고 DM이나 단체 Private 방 초대시 방 리스트 추가 예정입니다. 
- 게임 초대가 올 경우 Dm으로 메시지를 받고 수락할 경우 Nav로 /game으로 보내는 것이 어떠냐는 의견이 나왔습니다. 
- 유저가 나가고 들어올 때 웹소켓을 통해 리스트를 전달받아 참여중인 유저 리스트를 업데이트 할 예정입니다. 
- 본 브랜치는 에러가 있으니 머지는 하지 마시길...^^ 
## 개요

2022-08-15 12:53 UTC, scarf005 requested changes
전체적인 구조가 잘 짜인 것 같습니다. 표시된 부분만 확인해주시면 좋을 것 같아요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/router/Main.tsx
> +// }
```suggestion
import { Message, ClientToServerEvents, ServerToClientEvents } from 'data'
```
[frontend/app/src/data](https://github.com/exciting-transcendence/transcendence/blob/1d2f8184c58e753d439fa1164f14b5f9a6634e26/frontend/app/src/data/Chat.dto.ts) 에 관련 정보들을 담아뒀어요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/router/Main.tsx
> +    })
```suggestion
    const socket: Socket<ServerToClientEvents, ClientToServerEvents> = io('/api/chat', {
      auth: { token: window.localStorage.getItem('access_token') },
    })
```
이렇게 사용하면 enum으로 확인할 필요 없이 각 메소드별로 타입 체크를 받을 수 있어요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/ChatList.tsx
> +import Stack from '@mui/material/Stack'
```suggestion
import { Box, Paper, Stack } from '@mui/material'
```
하나로 합쳐주시면 좋을 것 같아요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/ChatList.tsx
> +}
`data/` 디렉토리에 인터페이스로 바꾸어서 보관주시면 좋을 것 같아요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/ChatView.tsx
>  }
타입 선언이 중복되는 곳이 있는 것 같습니다

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/CreateRoomModal.tsx
> +}
여기도 타입 선언이 겹치는 것 같아요

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/CreateRoomModal.tsx
> +}) {
```suggestion
export const BasicModal = (prop: {
  modal: boolean
  setModal: (value: boolean) => void
  socket: any
}) => {
```
되도록이면 default보다는 모듈 (`index.ts`)를 사용해서 import 하는 편이 좋을 것 같습니다

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/JoinedRoomList.tsx
> +import Stack from '@mui/material/Stack'
```suggestion
import { Box, Paper, Stack } from '@mui/material'
```

2022-08-15 12:53 UTC, scarf005 commented on frontend/app/src/view/JoinedRoomList.tsx
> +}
여기도 타입이 겹치네요

2022-08-15 17:13 UTC, scarf005 approved these changes
변경 내용 모두 확인했습니다. 수고 많으셨어요!

2022-08-15 17:13 UTC, scarf005 commented on frontend/app/src/view/CreateRoomModal.tsx
> +import Modal from '@mui/material/Modal'
```suggestion
  Typography,
  Modal,
} from '@mui/material'
```

2022-08-15 17:13 UTC, scarf005 commented on frontend/app/src/view/ChatView.tsx
>  }
여기는 계속 사용 예정인가요?

2022-08-16 02:09 UTC, peas856 commented on frontend/app/src/view/ChatView.tsx
>  }
제거했습니다

2022-08-16 02:09 UTC, merged